language: python

python:
  - "3.9"

cache: 
  pip:
  directories:
    - ./aws

install:
  - pip install --quiet --upgrade --requirement requirements.txt
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi

script:
  - make check lint test
  - make clean build
  - make deploy ENVIRONMENT="Staging" PLATFORM="Travis CI" FUNCTION=${STAGING_FUNCTION_NAME} VERSION=${TRAVIS_COMMIT} BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - make testdeployment URL=${STAGING_URL}
  - make deploy ENVIRONMENT="Production" PLATFORM="Travis CI" FUNCTION=${PRODUCTION_FUNCTION_NAME} VERSION=${TRAVIS_COMMIT} BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - make testdeployment URL=${PRODUCTION_URL}
